//Produit action

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_FAILURE = "SET_CURRENT_USER_FAILURE";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export const FETCH_PRODUIT_REQUEST = "FETCH_PRODUIT_REQUEST";
export const FETCH_PRODUIT_SUCCES = "FETCH_PRODUIT_SUCCES";
export const FETCH_PRODUIT_FAILURE = "FETCH_PRODUIT_FAILURE";

export const FETCH_HISTORY_REQUEST = "FETCH_HISTORY_REQUEST";
export const FETCH_HISTORY_SUCCES = "FETCH_HISTORY_SUCCES";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";
